server:
  port: 8088

#spring:
#  datasource:                                           # 数据源的相关配置
#    url: jdbc:mysql://47.100.58.26:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    username: root
#    password: 1qaz2wsx

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 11111111
  redis:
    database: 1
    host: 47.100.58.26
    port: 6379
    password: 111111

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl